version: "3"
services:
  ci-###:
    image: gitlab.finki.ukim.mk:5050/wp/###/###:dev
    container_name: ci-###
    ports:
      - "127.0.0.1:90$$:8080"
    environment:
      - spring.datasource.url=jdbc:postgresql://ci-db:5432/finki-services-db
      - spring.datasource.password=${DB_PASSWORD:-f1nk1_@dm1n}
      - spring.jpa.show-sql=false
    networks:
      - ci-services

networks:
  ci-services:
    external: true